/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/vue-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationReturnType
} from '@tanstack/vue-query';

import {
  toValue
} from 'vue';
import type {
  MaybeRefOrGetter
} from 'vue';

import type {
  ChatRequest,
  DocumentProcessRequest,
  ResultString,
  SseEmitter
} from './models';

import { customInstance } from '../utils/matutor/custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 流式输出并输出引用文档
 * @summary AI对话
 */
export const streamChat = (
    chatRequest: MaybeRefOrGetter<ChatRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      chatRequest = toValue(chatRequest);

      return customInstance<SseEmitter>(
      {url: `/api/ai/stream/chat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: chatRequest, signal
    },
      options);
    }




export const getStreamChatMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof streamChat>>, TError,{data: ChatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof streamChat>>, TError,{data: ChatRequest}, TContext> => {

const mutationKey = ['streamChat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof streamChat>>, {data: ChatRequest}> = (props) => {
          const {data} = props ?? {};

          return  streamChat(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StreamChatMutationResult = NonNullable<Awaited<ReturnType<typeof streamChat>>>
    export type StreamChatMutationBody = ChatRequest
    export type StreamChatMutationError = unknown

    /**
 * @summary AI对话
 */
export const useStreamChat = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof streamChat>>, TError,{data: ChatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof streamChat>>,
        TError,
        {data: ChatRequest},
        TContext
      > => {
      return useMutation(getStreamChatMutationOptions(options), queryClient);
    }
    /**
 * 用于测试 SSE 流，不实际调用 Python 服务
 * @summary 模拟AI对话（测试）
 */
export const mockStreamChat = (
    chatRequest: MaybeRefOrGetter<ChatRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      chatRequest = toValue(chatRequest);

      return customInstance<SseEmitter>(
      {url: `/api/ai/stream/chat/mock`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: chatRequest, signal
    },
      options);
    }




export const getMockStreamChatMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mockStreamChat>>, TError,{data: ChatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof mockStreamChat>>, TError,{data: ChatRequest}, TContext> => {

const mutationKey = ['mockStreamChat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof mockStreamChat>>, {data: ChatRequest}> = (props) => {
          const {data} = props ?? {};

          return  mockStreamChat(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MockStreamChatMutationResult = NonNullable<Awaited<ReturnType<typeof mockStreamChat>>>
    export type MockStreamChatMutationBody = ChatRequest
    export type MockStreamChatMutationError = unknown

    /**
 * @summary 模拟AI对话（测试）
 */
export const useMockStreamChat = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mockStreamChat>>, TError,{data: ChatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof mockStreamChat>>,
        TError,
        {data: ChatRequest},
        TContext
      > => {
      return useMutation(getMockStreamChatMutationOptions(options), queryClient);
    }
    /**
 * 处理当前用户拥有的文档
 * @summary 处理已有文件
 */
export const processExistingDocument = (
    documentProcessRequest: MaybeRefOrGetter<DocumentProcessRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      documentProcessRequest = toValue(documentProcessRequest);

      return customInstance<ResultString>(
      {url: `/api/ai/process`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: documentProcessRequest, signal
    },
      options);
    }




export const getProcessExistingDocumentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processExistingDocument>>, TError,{data: DocumentProcessRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof processExistingDocument>>, TError,{data: DocumentProcessRequest}, TContext> => {

const mutationKey = ['processExistingDocument'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof processExistingDocument>>, {data: DocumentProcessRequest}> = (props) => {
          const {data} = props ?? {};

          return  processExistingDocument(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProcessExistingDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof processExistingDocument>>>
    export type ProcessExistingDocumentMutationBody = DocumentProcessRequest
    export type ProcessExistingDocumentMutationError = unknown

    /**
 * @summary 处理已有文件
 */
export const useProcessExistingDocument = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processExistingDocument>>, TError,{data: DocumentProcessRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof processExistingDocument>>,
        TError,
        {data: DocumentProcessRequest},
        TContext
      > => {
      return useMutation(getProcessExistingDocumentMutationOptions(options), queryClient);
    }
