/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  toValue,
  unref
} from 'vue';
import type {
  MaybeRefOrGetter
} from 'vue';

import type {
  DeleteSessionParams,
  ListHistoryParams,
  ListSessionsParams,
  Result,
  ResultCursorPageResultChatMessage,
  ResultCursorPageResultChatSession
} from './models';

import { customInstance } from '../utils/matutor/custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const listHistory = (
    params: MaybeRefOrGetter<ListHistoryParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = toValue(params);

      return customInstance<ResultCursorPageResultChatMessage>(
      {url: `/api/ai/list`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListHistoryQueryKey = (params?: MaybeRefOrGetter<ListHistoryParams>,) => {
    return [
    'api','ai','list', ...(params ? [params] : [])
    ] as const;
    }


export const getListHistoryQueryOptions = <TData = Awaited<ReturnType<typeof listHistory>>, TError = unknown>(params: MaybeRefOrGetter<ListHistoryParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListHistoryQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listHistory>>> = ({ signal }) => listHistory(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listHistory>>, TError, TData>
}

export type ListHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof listHistory>>>
export type ListHistoryQueryError = unknown



export function useListHistory<TData = Awaited<ReturnType<typeof listHistory>>, TError = unknown>(
 params: MaybeRefOrGetter<ListHistoryParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}






export const listSessions = (
    params?: MaybeRefOrGetter<ListSessionsParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = toValue(params);

      return customInstance<ResultCursorPageResultChatSession>(
      {url: `/api/ai/list-session`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListSessionsQueryKey = (params?: MaybeRefOrGetter<ListSessionsParams>,) => {
    return [
    'api','ai','list-session', ...(params ? [params] : [])
    ] as const;
    }


export const getListSessionsQueryOptions = <TData = Awaited<ReturnType<typeof listSessions>>, TError = unknown>(params?: MaybeRefOrGetter<ListSessionsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListSessionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSessions>>> = ({ signal }) => listSessions(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>
}

export type ListSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof listSessions>>>
export type ListSessionsQueryError = unknown



export function useListSessions<TData = Awaited<ReturnType<typeof listSessions>>, TError = unknown>(
 params?: MaybeRefOrGetter<ListSessionsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSessionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}






export const deleteSession = (
    params: MaybeRefOrGetter<DeleteSessionParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = toValue(params);

      return customInstance<Result>(
      {url: `/api/ai/delete`, method: 'DELETE',
        params, signal
    },
      options);
    }




export const getDeleteSessionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSession>>, TError,{params: DeleteSessionParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSession>>, TError,{params: DeleteSessionParams}, TContext> => {

const mutationKey = ['deleteSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSession>>, {params: DeleteSessionParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteSession(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSessionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSession>>>

    export type DeleteSessionMutationError = unknown

    export const useDeleteSession = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSession>>, TError,{params: DeleteSessionParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteSession>>,
        TError,
        {params: DeleteSessionParams},
        TContext
      > => {
      return useMutation(getDeleteSessionMutationOptions(options), queryClient);
    }
