/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  toValue,
  unref
} from 'vue';
import type {
  MaybeRefOrGetter
} from 'vue';

import type {
  PutParams,
  Result,
  SearchParams
} from './models';

import { customInstance } from '../utils/matutor/custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const search = (
    params: MaybeRefOrGetter<SearchParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = toValue(params);

      return customInstance<Result>(
      {url: `/api/test/search`, method: 'GET',
        params, signal
    },
      options);
    }




export const getSearchQueryKey = (params?: MaybeRefOrGetter<SearchParams>,) => {
    return [
    'api','test','search', ...(params ? [params] : [])
    ] as const;
    }


export const getSearchQueryOptions = <TData = Awaited<ReturnType<typeof search>>, TError = unknown>(params: MaybeRefOrGetter<SearchParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getSearchQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof search>>> = ({ signal }) => search(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
}

export type SearchQueryResult = NonNullable<Awaited<ReturnType<typeof search>>>
export type SearchQueryError = unknown



export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = unknown>(
 params: MaybeRefOrGetter<SearchParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}






export const put = (
    params: MaybeRefOrGetter<PutParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = toValue(params);

      return customInstance<Result>(
      {url: `/api/test/put`, method: 'GET',
        params, signal
    },
      options);
    }




export const getPutQueryKey = (params?: MaybeRefOrGetter<PutParams>,) => {
    return [
    'api','test','put', ...(params ? [params] : [])
    ] as const;
    }


export const getPutQueryOptions = <TData = Awaited<ReturnType<typeof put>>, TError = unknown>(params: MaybeRefOrGetter<PutParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof put>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getPutQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof put>>> = ({ signal }) => put(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof put>>, TError, TData>
}

export type PutQueryResult = NonNullable<Awaited<ReturnType<typeof put>>>
export type PutQueryError = unknown



export function usePut<TData = Awaited<ReturnType<typeof put>>, TError = unknown>(
 params: MaybeRefOrGetter<PutParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof put>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPutQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}






