/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  toValue,
  unref
} from 'vue';
import type {
  MaybeRefOrGetter
} from 'vue';

import type {
  GenerateDownloadUrlParams,
  InitRequestV2,
  ListPartsParams,
  MergeRequestV2,
  ResultInitResponseV2,
  ResultListPartInfo,
  ResultString
} from './models';

import { customInstance } from '../utils/matutor/custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const completeMultipartUpload = (
    mergeRequestV2: MaybeRefOrGetter<MergeRequestV2>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      mergeRequestV2 = toValue(mergeRequestV2);

      return customInstance<ResultString>(
      {url: `/api/v2/storage/merge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mergeRequestV2, signal
    },
      options);
    }




export const getCompleteMultipartUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeMultipartUpload>>, TError,{data: MergeRequestV2}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof completeMultipartUpload>>, TError,{data: MergeRequestV2}, TContext> => {

const mutationKey = ['completeMultipartUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeMultipartUpload>>, {data: MergeRequestV2}> = (props) => {
          const {data} = props ?? {};

          return  completeMultipartUpload(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompleteMultipartUploadMutationResult = NonNullable<Awaited<ReturnType<typeof completeMultipartUpload>>>
    export type CompleteMultipartUploadMutationBody = MergeRequestV2
    export type CompleteMultipartUploadMutationError = unknown

    export const useCompleteMultipartUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeMultipartUpload>>, TError,{data: MergeRequestV2}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof completeMultipartUpload>>,
        TError,
        {data: MergeRequestV2},
        TContext
      > => {
      return useMutation(getCompleteMultipartUploadMutationOptions(options), queryClient);
    }
    export const initUpload = (
    initRequestV2: MaybeRefOrGetter<InitRequestV2>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      initRequestV2 = toValue(initRequestV2);

      return customInstance<ResultInitResponseV2>(
      {url: `/api/v2/storage/init`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: initRequestV2, signal
    },
      options);
    }




export const getInitUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initUpload>>, TError,{data: InitRequestV2}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof initUpload>>, TError,{data: InitRequestV2}, TContext> => {

const mutationKey = ['initUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof initUpload>>, {data: InitRequestV2}> = (props) => {
          const {data} = props ?? {};

          return  initUpload(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InitUploadMutationResult = NonNullable<Awaited<ReturnType<typeof initUpload>>>
    export type InitUploadMutationBody = InitRequestV2
    export type InitUploadMutationError = unknown

    export const useInitUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initUpload>>, TError,{data: InitRequestV2}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof initUpload>>,
        TError,
        {data: InitRequestV2},
        TContext
      > => {
      return useMutation(getInitUploadMutationOptions(options), queryClient);
    }
    export const listParts = (
    params: MaybeRefOrGetter<ListPartsParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = toValue(params);

      return customInstance<ResultListPartInfo>(
      {url: `/api/v2/storage/listParts`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListPartsQueryKey = (params?: MaybeRefOrGetter<ListPartsParams>,) => {
    return [
    'api','v2','storage','listParts', ...(params ? [params] : [])
    ] as const;
    }


export const getListPartsQueryOptions = <TData = Awaited<ReturnType<typeof listParts>>, TError = unknown>(params: MaybeRefOrGetter<ListPartsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListPartsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listParts>>> = ({ signal }) => listParts(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listParts>>, TError, TData>
}

export type ListPartsQueryResult = NonNullable<Awaited<ReturnType<typeof listParts>>>
export type ListPartsQueryError = unknown



export function useListParts<TData = Awaited<ReturnType<typeof listParts>>, TError = unknown>(
 params: MaybeRefOrGetter<ListPartsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listParts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPartsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}






export const generateDownloadUrl = (
    params: MaybeRefOrGetter<GenerateDownloadUrlParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = toValue(params);

      return customInstance<ResultString>(
      {url: `/api/v2/storage/Download`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGenerateDownloadUrlQueryKey = (params?: MaybeRefOrGetter<GenerateDownloadUrlParams>,) => {
    return [
    'api','v2','storage','Download', ...(params ? [params] : [])
    ] as const;
    }


export const getGenerateDownloadUrlQueryOptions = <TData = Awaited<ReturnType<typeof generateDownloadUrl>>, TError = unknown>(params: MaybeRefOrGetter<GenerateDownloadUrlParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof generateDownloadUrl>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGenerateDownloadUrlQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof generateDownloadUrl>>> = ({ signal }) => generateDownloadUrl(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof generateDownloadUrl>>, TError, TData>
}

export type GenerateDownloadUrlQueryResult = NonNullable<Awaited<ReturnType<typeof generateDownloadUrl>>>
export type GenerateDownloadUrlQueryError = unknown



export function useGenerateDownloadUrl<TData = Awaited<ReturnType<typeof generateDownloadUrl>>, TError = unknown>(
 params: MaybeRefOrGetter<GenerateDownloadUrlParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof generateDownloadUrl>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGenerateDownloadUrlQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}






