/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  toValue,
  unref
} from 'vue';
import type {
  MaybeRefOrGetter
} from 'vue';

import type {
  DeleteRequest,
  ListRecycleBinFilesParams,
  RestoreRequest,
  Result,
  ResultPageResultRecycleFileVO
} from './models';

import { customInstance } from '../utils/matutor/custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 还原文件或文件夹
 * @summary 还原文件/文件夹
 */
export const restore = (
    restoreRequest: MaybeRefOrGetter<RestoreRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      restoreRequest = toValue(restoreRequest);

      return customInstance<Result>(
      {url: `/api/recycle/restore`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: restoreRequest, signal
    },
      options);
    }




export const getRestoreMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restore>>, TError,{data: RestoreRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof restore>>, TError,{data: RestoreRequest}, TContext> => {

const mutationKey = ['restore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof restore>>, {data: RestoreRequest}> = (props) => {
          const {data} = props ?? {};

          return  restore(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RestoreMutationResult = NonNullable<Awaited<ReturnType<typeof restore>>>
    export type RestoreMutationBody = RestoreRequest
    export type RestoreMutationError = unknown

    /**
 * @summary 还原文件/文件夹
 */
export const useRestore = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restore>>, TError,{data: RestoreRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof restore>>,
        TError,
        {data: RestoreRequest},
        TContext
      > => {
      return useMutation(getRestoreMutationOptions(options), queryClient);
    }
    /**
 * 查询回收站内所有文件和文件夹
 * @summary 获取回收站文件列表
 */
export const listRecycleBinFiles = (
    params: MaybeRefOrGetter<ListRecycleBinFilesParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = toValue(params);

      return customInstance<ResultPageResultRecycleFileVO>(
      {url: `/api/recycle`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListRecycleBinFilesQueryKey = (params?: MaybeRefOrGetter<ListRecycleBinFilesParams>,) => {
    return [
    'api','recycle', ...(params ? [params] : [])
    ] as const;
    }


export const getListRecycleBinFilesQueryOptions = <TData = Awaited<ReturnType<typeof listRecycleBinFiles>>, TError = unknown>(params: MaybeRefOrGetter<ListRecycleBinFilesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecycleBinFiles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListRecycleBinFilesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRecycleBinFiles>>> = ({ signal }) => listRecycleBinFiles(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRecycleBinFiles>>, TError, TData>
}

export type ListRecycleBinFilesQueryResult = NonNullable<Awaited<ReturnType<typeof listRecycleBinFiles>>>
export type ListRecycleBinFilesQueryError = unknown


/**
 * @summary 获取回收站文件列表
 */

export function useListRecycleBinFiles<TData = Awaited<ReturnType<typeof listRecycleBinFiles>>, TError = unknown>(
 params: MaybeRefOrGetter<ListRecycleBinFilesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRecycleBinFiles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListRecycleBinFilesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}






/**
 * 彻底删除文件/文件夹
 * @summary 批量彻底删除
 */
export const deletePermanently = (
    deleteRequest: MaybeRefOrGetter<DeleteRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      deleteRequest = toValue(deleteRequest);

      return customInstance<Result>(
      {url: `/api/recycle/permanent`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteRequest, signal
    },
      options);
    }




export const getDeletePermanentlyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePermanently>>, TError,{data: DeleteRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePermanently>>, TError,{data: DeleteRequest}, TContext> => {

const mutationKey = ['deletePermanently'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePermanently>>, {data: DeleteRequest}> = (props) => {
          const {data} = props ?? {};

          return  deletePermanently(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePermanentlyMutationResult = NonNullable<Awaited<ReturnType<typeof deletePermanently>>>
    export type DeletePermanentlyMutationBody = DeleteRequest
    export type DeletePermanentlyMutationError = unknown

    /**
 * @summary 批量彻底删除
 */
export const useDeletePermanently = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePermanently>>, TError,{data: DeleteRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deletePermanently>>,
        TError,
        {data: DeleteRequest},
        TContext
      > => {
      return useMutation(getDeletePermanentlyMutationOptions(options), queryClient);
    }
