/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  toValue,
  unref
} from 'vue';
import type {
  MaybeRefOrGetter
} from 'vue';

import type {
  CancelRequest,
  GetDownloadUrlByKeyParams,
  InitRequest,
  MergeRequest,
  Result,
  ResultString,
  ResultUploadProgress,
  ResultUploadSession,
  ResultVoid,
  UploadChunkBody
} from './models';

import { customInstance } from '../utils/matutor/custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary 合并分片
 */
export const mergeChunks = (
    mergeRequest: MaybeRefOrGetter<MergeRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      mergeRequest = toValue(mergeRequest);

      return customInstance<Result>(
      {url: `/api/storage/upload/merge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mergeRequest, signal
    },
      options);
    }




export const getMergeChunksMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mergeChunks>>, TError,{data: MergeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof mergeChunks>>, TError,{data: MergeRequest}, TContext> => {

const mutationKey = ['mergeChunks'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof mergeChunks>>, {data: MergeRequest}> = (props) => {
          const {data} = props ?? {};

          return  mergeChunks(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MergeChunksMutationResult = NonNullable<Awaited<ReturnType<typeof mergeChunks>>>
    export type MergeChunksMutationBody = MergeRequest
    export type MergeChunksMutationError = unknown

    /**
 * @summary 合并分片
 */
export const useMergeChunks = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mergeChunks>>, TError,{data: MergeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof mergeChunks>>,
        TError,
        {data: MergeRequest},
        TContext
      > => {
      return useMutation(getMergeChunksMutationOptions(options), queryClient);
    }
    /**
 * @summary 初始化上传会话
 */
export const initUpload1 = (
    initRequest: MaybeRefOrGetter<InitRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      initRequest = toValue(initRequest);

      return customInstance<ResultUploadSession>(
      {url: `/api/storage/upload/init`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: initRequest, signal
    },
      options);
    }




export const getInitUpload1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initUpload1>>, TError,{data: InitRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof initUpload1>>, TError,{data: InitRequest}, TContext> => {

const mutationKey = ['initUpload1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof initUpload1>>, {data: InitRequest}> = (props) => {
          const {data} = props ?? {};

          return  initUpload1(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InitUpload1MutationResult = NonNullable<Awaited<ReturnType<typeof initUpload1>>>
    export type InitUpload1MutationBody = InitRequest
    export type InitUpload1MutationError = unknown

    /**
 * @summary 初始化上传会话
 */
export const useInitUpload1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initUpload1>>, TError,{data: InitRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof initUpload1>>,
        TError,
        {data: InitRequest},
        TContext
      > => {
      return useMutation(getInitUpload1MutationOptions(options), queryClient);
    }
    /**
 * @summary 上传分片
 */
export const uploadChunk = (
    uploadChunkBody?: MaybeRefOrGetter<UploadChunkBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      uploadChunkBody = toValue(uploadChunkBody);
      const formData = new FormData();
if(uploadChunkBody?.request !== undefined) {
 formData.append(`request`, JSON.stringify(uploadChunkBody.request));
 }
if(uploadChunkBody?.chunk !== undefined) {
 formData.append(`chunk`, uploadChunkBody.chunk);
 }

      return customInstance<ResultUploadProgress>(
      {url: `/api/storage/upload/chunk`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }




export const getUploadChunkMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadChunk>>, TError,{data?: UploadChunkBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadChunk>>, TError,{data?: UploadChunkBody}, TContext> => {

const mutationKey = ['uploadChunk'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadChunk>>, {data?: UploadChunkBody}> = (props) => {
          const {data} = props ?? {};

          return  uploadChunk(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadChunkMutationResult = NonNullable<Awaited<ReturnType<typeof uploadChunk>>>
    export type UploadChunkMutationBody = UploadChunkBody | undefined
    export type UploadChunkMutationError = unknown

    /**
 * @summary 上传分片
 */
export const useUploadChunk = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadChunk>>, TError,{data?: UploadChunkBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof uploadChunk>>,
        TError,
        {data?: UploadChunkBody},
        TContext
      > => {
      return useMutation(getUploadChunkMutationOptions(options), queryClient);
    }
    /**
 * @summary 取消上传
 */
export const cancelUpload = (
    cancelRequest: MaybeRefOrGetter<CancelRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      cancelRequest = toValue(cancelRequest);

      return customInstance<ResultVoid>(
      {url: `/api/storage/upload/cancel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cancelRequest, signal
    },
      options);
    }




export const getCancelUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelUpload>>, TError,{data: CancelRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cancelUpload>>, TError,{data: CancelRequest}, TContext> => {

const mutationKey = ['cancelUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelUpload>>, {data: CancelRequest}> = (props) => {
          const {data} = props ?? {};

          return  cancelUpload(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CancelUploadMutationResult = NonNullable<Awaited<ReturnType<typeof cancelUpload>>>
    export type CancelUploadMutationBody = CancelRequest
    export type CancelUploadMutationError = unknown

    /**
 * @summary 取消上传
 */
export const useCancelUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelUpload>>, TError,{data: CancelRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof cancelUpload>>,
        TError,
        {data: CancelRequest},
        TContext
      > => {
      return useMutation(getCancelUploadMutationOptions(options), queryClient);
    }
    /**
 * @summary 查询上传进度
 */
export const getProgress = (
    sessionId: MaybeRefOrGetter<string>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      sessionId = toValue(sessionId);

      return customInstance<ResultUploadProgress>(
      {url: `/api/storage/upload/progress/${sessionId}`, method: 'GET', signal
    },
      options);
    }




export const getGetProgressQueryKey = (sessionId: MaybeRefOrGetter<string>,) => {
    return [
    'api','storage','upload','progress',sessionId
    ] as const;
    }


export const getGetProgressQueryOptions = <TData = Awaited<ReturnType<typeof getProgress>>, TError = unknown>(sessionId: MaybeRefOrGetter<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgress>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetProgressQueryKey(sessionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProgress>>> = ({ signal }) => getProgress(sessionId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: computed(() => toValue(sessionId) !== null && toValue(sessionId) !== undefined), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProgress>>, TError, TData>
}

export type GetProgressQueryResult = NonNullable<Awaited<ReturnType<typeof getProgress>>>
export type GetProgressQueryError = unknown


/**
 * @summary 查询上传进度
 */

export function useGetProgress<TData = Awaited<ReturnType<typeof getProgress>>, TError = unknown>(
 sessionId: MaybeRefOrGetter<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgress>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProgressQueryOptions(sessionId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}






/**
 * @summary 根据存储Key获取下载链接（通用）
 */
export const getDownloadUrlByKey = (
    params: MaybeRefOrGetter<GetDownloadUrlByKeyParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = toValue(params);

      return customInstance<ResultString>(
      {url: `/api/storage/download-url/by-key`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetDownloadUrlByKeyQueryKey = (params?: MaybeRefOrGetter<GetDownloadUrlByKeyParams>,) => {
    return [
    'api','storage','download-url','by-key', ...(params ? [params] : [])
    ] as const;
    }


export const getGetDownloadUrlByKeyQueryOptions = <TData = Awaited<ReturnType<typeof getDownloadUrlByKey>>, TError = unknown>(params: MaybeRefOrGetter<GetDownloadUrlByKeyParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDownloadUrlByKey>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetDownloadUrlByKeyQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDownloadUrlByKey>>> = ({ signal }) => getDownloadUrlByKey(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDownloadUrlByKey>>, TError, TData>
}

export type GetDownloadUrlByKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getDownloadUrlByKey>>>
export type GetDownloadUrlByKeyQueryError = unknown


/**
 * @summary 根据存储Key获取下载链接（通用）
 */

export function useGetDownloadUrlByKey<TData = Awaited<ReturnType<typeof getDownloadUrlByKey>>, TError = unknown>(
 params: MaybeRefOrGetter<GetDownloadUrlByKeyParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDownloadUrlByKey>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDownloadUrlByKeyQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}






