/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  toValue,
  unref
} from 'vue';
import type {
  MaybeRefOrGetter
} from 'vue';

import type {
  CreateFolderRequest,
  DeleteRequest,
  ListFilesParams,
  ListFolderOnlyParams,
  MoveRequest,
  RenameRequest,
  Result,
  ResultListVirtualFileVO,
  ResultPageResultVirtualFileVO,
  SearchParams
} from './models';

import { customInstance } from '../utils/matutor/custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 重命名一个文件或文件夹
 * @summary 重命名文件/文件夹
 */
export const rename = (
    renameRequest: MaybeRefOrGetter<RenameRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      renameRequest = toValue(renameRequest);

      return customInstance<Result>(
      {url: `/api/files/rename`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: renameRequest, signal
    },
      options);
    }




export const getRenameMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rename>>, TError,{data: RenameRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof rename>>, TError,{data: RenameRequest}, TContext> => {

const mutationKey = ['rename'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rename>>, {data: RenameRequest}> = (props) => {
          const {data} = props ?? {};

          return  rename(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RenameMutationResult = NonNullable<Awaited<ReturnType<typeof rename>>>
    export type RenameMutationBody = RenameRequest
    export type RenameMutationError = unknown

    /**
 * @summary 重命名文件/文件夹
 */
export const useRename = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rename>>, TError,{data: RenameRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof rename>>,
        TError,
        {data: RenameRequest},
        TContext
      > => {
      return useMutation(getRenameMutationOptions(options), queryClient);
    }
    /**
 * 将文件/文件夹移动到指定父目录下
 * @summary 移动文件/文件夹
 */
export const moveTo = (
    moveRequest: MaybeRefOrGetter<MoveRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      moveRequest = toValue(moveRequest);

      return customInstance<Result>(
      {url: `/api/files/move-to`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: moveRequest, signal
    },
      options);
    }




export const getMoveToMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveTo>>, TError,{data: MoveRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof moveTo>>, TError,{data: MoveRequest}, TContext> => {

const mutationKey = ['moveTo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof moveTo>>, {data: MoveRequest}> = (props) => {
          const {data} = props ?? {};

          return  moveTo(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MoveToMutationResult = NonNullable<Awaited<ReturnType<typeof moveTo>>>
    export type MoveToMutationBody = MoveRequest
    export type MoveToMutationError = unknown

    /**
 * @summary 移动文件/文件夹
 */
export const useMoveTo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveTo>>, TError,{data: MoveRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof moveTo>>,
        TError,
        {data: MoveRequest},
        TContext
      > => {
      return useMutation(getMoveToMutationOptions(options), queryClient);
    }
    /**
 * 在指定的父目录下创建一个新文件夹
 * @summary 新建文件夹
 */
export const createFolder = (
    createFolderRequest: MaybeRefOrGetter<CreateFolderRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      createFolderRequest = toValue(createFolderRequest);

      return customInstance<Result>(
      {url: `/api/files/folders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFolderRequest, signal
    },
      options);
    }




export const getCreateFolderMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFolder>>, TError,{data: CreateFolderRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createFolder>>, TError,{data: CreateFolderRequest}, TContext> => {

const mutationKey = ['createFolder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFolder>>, {data: CreateFolderRequest}> = (props) => {
          const {data} = props ?? {};

          return  createFolder(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateFolderMutationResult = NonNullable<Awaited<ReturnType<typeof createFolder>>>
    export type CreateFolderMutationBody = CreateFolderRequest
    export type CreateFolderMutationError = unknown

    /**
 * @summary 新建文件夹
 */
export const useCreateFolder = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFolder>>, TError,{data: CreateFolderRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createFolder>>,
        TError,
        {data: CreateFolderRequest},
        TContext
      > => {
      return useMutation(getCreateFolderMutationOptions(options), queryClient);
    }
    /**
 * 根据关键词模糊搜索文件和文件夹，支持分页
 * @summary 搜索文件/文件夹
 */
export const search = (
    params: MaybeRefOrGetter<SearchParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = toValue(params);

      return customInstance<ResultPageResultVirtualFileVO>(
      {url: `/api/files/search`, method: 'GET',
        params, signal
    },
      options);
    }




export const getSearchQueryKey = (params?: MaybeRefOrGetter<SearchParams>,) => {
    return [
    'api','files','search', ...(params ? [params] : [])
    ] as const;
    }


export const getSearchQueryOptions = <TData = Awaited<ReturnType<typeof search>>, TError = unknown>(params: MaybeRefOrGetter<SearchParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getSearchQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof search>>> = ({ signal }) => search(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
}

export type SearchQueryResult = NonNullable<Awaited<ReturnType<typeof search>>>
export type SearchQueryError = unknown


/**
 * @summary 搜索文件/文件夹
 */

export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = unknown>(
 params: MaybeRefOrGetter<SearchParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}






/**
 * 根据父目录ID查询该目录下的子文件夹
 * @summary 仅获取文件夹列表
 */
export const listFolderOnly = (
    params?: MaybeRefOrGetter<ListFolderOnlyParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = toValue(params);

      return customInstance<ResultListVirtualFileVO>(
      {url: `/api/files/list-folderOnly`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListFolderOnlyQueryKey = (params?: MaybeRefOrGetter<ListFolderOnlyParams>,) => {
    return [
    'api','files','list-folderOnly', ...(params ? [params] : [])
    ] as const;
    }


export const getListFolderOnlyQueryOptions = <TData = Awaited<ReturnType<typeof listFolderOnly>>, TError = unknown>(params?: MaybeRefOrGetter<ListFolderOnlyParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFolderOnly>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListFolderOnlyQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFolderOnly>>> = ({ signal }) => listFolderOnly(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFolderOnly>>, TError, TData>
}

export type ListFolderOnlyQueryResult = NonNullable<Awaited<ReturnType<typeof listFolderOnly>>>
export type ListFolderOnlyQueryError = unknown


/**
 * @summary 仅获取文件夹列表
 */

export function useListFolderOnly<TData = Awaited<ReturnType<typeof listFolderOnly>>, TError = unknown>(
 params?: MaybeRefOrGetter<ListFolderOnlyParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFolderOnly>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFolderOnlyQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}






/**
 * 根据父目录ID查询该目录下的所有文件和子文件夹
 * @summary 获取文件列表
 */
export const listFiles = (
    params?: MaybeRefOrGetter<ListFilesParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = toValue(params);

      return customInstance<ResultListVirtualFileVO>(
      {url: `/api/files/list-file`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListFilesQueryKey = (params?: MaybeRefOrGetter<ListFilesParams>,) => {
    return [
    'api','files','list-file', ...(params ? [params] : [])
    ] as const;
    }


export const getListFilesQueryOptions = <TData = Awaited<ReturnType<typeof listFiles>>, TError = unknown>(params?: MaybeRefOrGetter<ListFilesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFiles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListFilesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFiles>>> = ({ signal }) => listFiles(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFiles>>, TError, TData>
}

export type ListFilesQueryResult = NonNullable<Awaited<ReturnType<typeof listFiles>>>
export type ListFilesQueryError = unknown


/**
 * @summary 获取文件列表
 */

export function useListFiles<TData = Awaited<ReturnType<typeof listFiles>>, TError = unknown>(
 params?: MaybeRefOrGetter<ListFilesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFiles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFilesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}






/**
 * 将文件/文件夹移入回收站
 * @summary 批量移入回收站
 */
export const moveToRecycleBin = (
    deleteRequest: MaybeRefOrGetter<DeleteRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      deleteRequest = toValue(deleteRequest);

      return customInstance<Result>(
      {url: `/api/files`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteRequest, signal
    },
      options);
    }




export const getMoveToRecycleBinMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveToRecycleBin>>, TError,{data: DeleteRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof moveToRecycleBin>>, TError,{data: DeleteRequest}, TContext> => {

const mutationKey = ['moveToRecycleBin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof moveToRecycleBin>>, {data: DeleteRequest}> = (props) => {
          const {data} = props ?? {};

          return  moveToRecycleBin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MoveToRecycleBinMutationResult = NonNullable<Awaited<ReturnType<typeof moveToRecycleBin>>>
    export type MoveToRecycleBinMutationBody = DeleteRequest
    export type MoveToRecycleBinMutationError = unknown

    /**
 * @summary 批量移入回收站
 */
export const useMoveToRecycleBin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveToRecycleBin>>, TError,{data: DeleteRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof moveToRecycleBin>>,
        TError,
        {data: DeleteRequest},
        TContext
      > => {
      return useMutation(getMoveToRecycleBinMutationOptions(options), queryClient);
    }
