/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 取消上传请求体
 */
export interface CancelRequest {
  /** 上传会话ID（由初始化接口返回） */
  sessionId: string;
}
