/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ChatSession {
  id?: number;
  sessionId?: string;
  userId?: number;
  title?: string;
  messageCount?: number;
  createTime?: string;
  updateTime?: string;
}
