/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ChatMessage {
  id?: number;
  sessionId?: string;
  role?: string;
  content?: string;
  createTime?: string;
}
