/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 创建分享的响应体
 */
export interface CreateShareResponse {
  /** 分享链接ID */
  id?: number;
  /** 分享链接唯一码(前端拼接URL) */
  shareCode?: string;
  /** 提取码 */
  password?: string;
  /** 过期时间 */
  expireTime?: string;
  /** 创建分享时间 */
  createTime?: string;
}
