/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 创建文件夹请求体
 */
export interface CreateFolderRequest {
  /** 父目录ID，若为0表示根目录 */
  parentId: number;
  /**
     * 文件夹名称
     * @minLength 1
     * @maxLength 255
     */
  name: string;
}
