/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ChatMessage } from './chatMessage';

/**
 * 响应数据
 */
export interface CursorPageResultChatMessage {
  list?: ChatMessage[];
  nextCursor?: string;
  hasNext?: boolean;
}
