/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ChatSession } from './chatSession';

/**
 * 响应数据
 */
export interface CursorPageResultChatSession {
  list?: ChatSession[];
  nextCursor?: string;
  hasNext?: boolean;
}
