/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ItemIdentity } from './itemIdentity';

/**
 * 批量删除请求体
 */
export interface DeleteRequest {
  /** 待删除的文件/文件夹标识列表（支持混合删除） */
  items?: ItemIdentity[];
}
