/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * RAG处理请求体
 */
export interface DocumentProcessRequest {
  /** 用户文件ID */
  id?: number;
}
