/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 文件/文件夹类型
 */
export type FileItemType = typeof FileItemType[keyof typeof FileItemType];


export const FileItemType = {
  FILE: 'FILE',
  FOLDER: 'FOLDER',
} as const;
