/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetShareInfoParams = {
/**
 * @minimum 0
 */
parentId: number;
/**
 * @minimum 0
 */
rootId: number;
};
