/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 初始化上传请求的请求体
 */
export interface InitRequest {
  /** 文件名 */
  fileName: string;
  /** 相对路径 */
  relativePath?: string;
  /** 文件大小（字节） */
  fileSize: number;
  /** 文件的前1MB的Md5 */
  md5: string;
  /** 分块的大小（字节） */
  chunkSize?: number;
  /** 父目录ID */
  parentId: number;
  /** 是否为文件夹上传 */
  isFolderUpload: boolean;
}
