/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface InitResponseV2 {
  uploadId?: string;
  chunkSize?: number;
  presignedUrls?: string[];
  uploadedChunks?: number[];
  isComplete?: boolean;
}
