/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 初始化上传请求的请求体
 */
export interface InitRequestV2 {
  /** 文件名 */
  fileName: string;
  /** 文件大小（字节） */
  fileSize: number;
  /** 文件的前1MB的Md5 */
  fileHash: string;
  /** 分块的大小（字节） */
  chunkSize?: number;
  parentId?: number;
  /** @nullable */
  relativePath?: string | null;
  totalChunks?: number;
  uploadId?: string;
}
