/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FileItemType } from './fileItemType';

/**
 * 简易对象实体
 */
export interface ItemIdentity {
  /**
     * 文件/文件夹ID
     * @minimum 1
     */
  id: number;
  type: FileItemType;
}
