/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ListSharedFileParams = {
/**
 * 页码
 * @minimum 0
 */
pageNum: number;
/**
 * 页大小
 * @minimum 0
 */
pageSize: number;
};
