/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ListFolderOnlyParams = {
/**
 * 父目录ID，若为0或null则自动定位到用户根目录
 */
parentId?: number;
};
