/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 响应数据
 */
export interface LoginResponse {
  /** 登录token */
  token: string;
  /** 昵称 */
  nickname?: string;
  username?: string;
  phone?: string;
  email?: string;
  /** 过期时间 */
  expiresIn?: number;
  /** 根目录Id */
  rootFolderId?: number;
  /** 根目录名称 */
  rootFolderName?: string;
}
