/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 取消上传请求体
 */
export interface LoginRequest {
  /** 登录凭证（目前为用户名） */
  loginAccount: string;
  /** 登录密码 */
  password: string;
}
