/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 合并请求体
 */
export interface MergeRequest {
  /** 会话ID */
  sessionId?: string;
}
