/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PartInfo } from './partInfo';

export interface MergeRequestV2 {
  uploadId?: string;
  parts?: PartInfo[];
}
