/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ItemIdentity } from './itemIdentity';

/**
 * 移动文件/文件夹的请求体
 */
export interface MoveRequest {
  /** 待删除的文件/文件夹标识列表（支持混合删除） */
  items?: ItemIdentity[];
  /** 目标父目录Id */
  parentId?: number;
}
