/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RegisterRequest {
  /**
     * 用户名
     * @minLength 3
     * @maxLength 20
     */
  username?: string;
  /** 邮箱 */
  email?: string;
  /**
     * 手机号码
     * @minLength 0
     * @maxLength 20
     */
  phone?: string;
  /**
     * 密码
     * @minLength 6
     * @maxLength 20
     */
  password: string;
}
