/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 响应数据
 */
export interface RegisterResponse {
  userId?: number;
  username?: string;
  email?: string;
  phone?: string;
}
