/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FileItemType } from './fileItemType';

/**
 * 用于文件/文件夹重命名的请求体
 */
export interface RenameRequest {
  /** 文件/文件夹Id */
  id?: number;
  /** 新名字 */
  newName?: string;
  type?: FileItemType;
}
