/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ItemIdentity } from './itemIdentity';

/**
 * 批量还原请求体
 */
export interface RestoreRequest {
  /** 待还原的文件/文件夹标识列表 */
  items?: ItemIdentity[];
}
