/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 通用响应对象
 */
export interface ResultString {
  /** 响应状态码，1表示成功 */
  code?: number;
  /** 响应消息 */
  msg?: string;
  /** 响应数据 */
  data?: string;
}
