/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PartInfo } from './partInfo';

/**
 * 通用响应对象
 */
export interface ResultListPartInfo {
  /** 响应状态码，1表示成功 */
  code?: number;
  /** 响应消息 */
  msg?: string;
  /** 响应数据 */
  data: PartInfo[];
}
