/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CursorPageResultChatSession } from './cursorPageResultChatSession';

/**
 * 通用响应对象
 */
export interface ResultCursorPageResultChatSession {
  /** 响应状态码，1表示成功 */
  code?: number;
  /** 响应消息 */
  msg?: string;
  data?: CursorPageResultChatSession;
}
