/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FileItemType } from './fileItemType';

/**
 * 分享的文件/文件夹对象
 */
export interface ShareItem {
  /** 文件/文件夹ID */
  targetId?: number;
  targetType?: FileItemType;
}
