/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ShareStatus } from './shareStatus';

/**
 * 用于前端返回的视图对象
 */
export interface ShareLinkVO {
  /** 分享链接ID */
  id?: number;
  /** 分享链接唯一码(前端拼接URL) */
  shareCode?: string;
  /** 提取码 */
  password?: string;
  /** 过期时间 */
  expireTime?: string;
  status?: ShareStatus;
  /** 创建时间 */
  createTime?: string;
  /** 最后更新时间 */
  updateTime?: string;
  /** 分享链接显示名称 */
  displayName?: string;
}
