/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 分享链接状态
 */
export type ShareStatus = typeof ShareStatus[keyof typeof ShareStatus];


export const ShareStatus = {
  NO_ACTIVE: 'NO_ACTIVE',
  ACTIVE: 'ACTIVE',
} as const;
