/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UploadChunkRequest } from './uploadChunkRequest';

export type UploadChunkBody = {
  request: UploadChunkRequest;
  /** 分片文件 */
  chunk: Blob;
};
