/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 响应数据
 */
export interface UploadSession {
  sessionId?: string;
  status?: string;
  userId?: number;
  fileName?: string;
  fileSize?: number;
  md5?: string;
  ossKey?: string;
  totalChunks?: number;
  parentId?: number;
  relativePath?: string;
  isFolderUpload?: boolean;
  presignedUrl?: string;
}
