/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 分片元数据
 */
export interface UploadChunkRequest {
  /** 会话ID */
  sessionId?: string;
  /** 分片索引，从0开始 */
  chunkIndex?: number;
  /** 整个分片的Md5 */
  md5?: string;
}
