/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 用于返回前端的上传进度查询返回体
 */
export interface UploadProgress {
  /** 会话ID */
  sessionId?: string;
  /** 文件名 */
  fileName?: string;
  /** 上传状态 */
  status?: string;
  /** 已上传分片 */
  uploadedChunks?: number;
  /** 总的分片数量 */
  totalChunks?: number;
  /** 上传进度 */
  progress?: number;
  /** 物理文件对象键 */
  ossKey?: string;
}
